window.IMPORTED_COLLEGES = [
  {
    "name": "Massachusetts Institute of Technology",
    "region": "Northeast",
    "state": "MA",
    "fullUndergrad": 4600,
    "gradRate": 96,
    "deadline": "January 5",
    "majorStrengths": ["Aerospace Engineering", "Physics", "Artificial Intelligence", "Mathematics"],
    "applications": 28200,
    "accepted": 1300,
    "outstate": 60000,
    "roomBoard": 19500,
    "books": 850,
    "personal": 2300,
    "phd": 100,
    "terminal": 100,
    "testOptional": false,
    "isPrivate": true,
    "satRange": [1520, 1580],
    "actRange": [34, 36],
    "promptHistory": ["2025: Describe something you do simply for the pleasure of it.", "2024: How have you contributed to your community?"],
    "extracurricularHighlights": ["MIT Media Lab", "Undergraduate Research Opportunities Program (UROP)", "Glass Lab"],
    "website": "https://www.mit.edu",
    "admissionsUrl": "https://mitadmissions.org"
  },
  {
    "name": "Georgetown University",
    "region": "South",
    "state": "DC",
    "fullUndergrad": 7500,
    "gradRate": 95,
    "deadline": "January 10",
    "majorStrengths": ["International Politics", "Law", "Nursing", "Finance"],
    "applications": 26000,
    "accepted": 3300,
    "outstate": 64500,
    "roomBoard": 19000,
    "books": 1200,
    "personal": 2800,
    "phd": 97,
    "terminal": 99,
    "testOptional": false,
    "isPrivate": true,
    "satRange": [1440, 1550],
    "actRange": [32, 35],
    "promptHistory": ["2025: Discuss a global issue you are passionate about.", "2024: Jesuit values and personal growth."],
    "extracurricularHighlights": ["The Hoya", "IRC (Model UN)", "The Corp (Student Business)"],
    "website": "https://www.georgetown.edu",
    "admissionsUrl": "https://gadmissions.georgetown.edu"
  },
  {
    "name": "University of Florida",
    "region": "South",
    "state": "FL",
    "fullUndergrad": 38000,
    "gradRate": 91,
    "deadline": "November 1",
    "majorStrengths": ["Agricultural Science", "Marketing", "Journalism", "Sports Management"],
    "applications": 68000,
    "accepted": 15600,
    "outstate": 28600,
    "roomBoard": 11500,
    "books": 900,
    "personal": 2200,
    "phd": 91,
    "terminal": 94,
    "testOptional": false,
    "isPrivate": false,
    "satRange": [1300, 1470],
    "actRange": [29, 33],
    "promptHistory": ["2024: Describe a meaningful community service activity."],
    "extracurricularHighlights": ["Dance Marathon", "Innovation Academy", "Gator Motorsports"],
    "website": "https://www.ufl.edu",
    "admissionsUrl": "https://admissions.ufl.edu"
  },
  {
    "name": "Williams College",
    "region": "Northeast",
    "state": "MA",
    "fullUndergrad": 2100,
    "gradRate": 96,
    "deadline": "January 1",
    "majorStrengths": ["Art History", "Economics", "English Literature", "Physics"],
    "applications": 11500,
    "accepted": 900,
    "outstate": 65000,
    "roomBoard": 16500,
    "books": 800,
    "personal": 1500,
    "phd": 100,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1490, 1560],
    "actRange": [33, 35],
    "promptHistory": ["2025: Share a time when you engaged with a different perspective.", "2024: Why Williams?"],
    "extracurricularHighlights": ["Oxford-style Tutorials", "Williams Outing Club", "The Record"],
    "website": "https://www.williams.edu",
    "admissionsUrl": "https://www.williams.edu/admission-aid"
  },
  {
    "name": "Harvey Mudd College",
    "region": "West",
    "state": "CA",
    "fullUndergrad": 900,
    "gradRate": 93,
    "deadline": "January 5",
    "majorStrengths": ["Engineering", "Computer Science", "Physics", "Chemistry"],
    "applications": 4500,
    "accepted": 600,
    "outstate": 66000,
    "roomBoard": 20000,
    "books": 800,
    "personal": 1200,
    "phd": 100,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1500, 1560],
    "actRange": [34, 35],
    "promptHistory": ["2025: Discuss an issue of social justice.", "2024: Why Harvey Mudd?"],
    "extracurricularHighlights": ["Clinic Program", "Claremont Consortium", "Mudd Amateur Rocketry"],
    "website": "https://www.hmc.edu",
    "admissionsUrl": "https://www.hmc.edu/admission"
  },
  {
    "name": "Villanova University",
    "region": "Northeast",
    "state": "PA",
    "fullUndergrad": 6700,
    "gradRate": 90,
    "deadline": "January 15",
    "majorStrengths": ["Finance", "Nursing", "Civil Engineering", "Liberal Arts"],
    "applications": 24000,
    "accepted": 5800,
    "outstate": 62500,
    "roomBoard": 16800,
    "books": 1000,
    "personal": 2000,
    "phd": 92,
    "terminal": 95,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1400, 1510],
    "actRange": [32, 34],
    "promptHistory": ["2025: What is 'Truth' in today's world?", "2024: Describe a community that made you who you are."],
    "extracurricularHighlights": ["Special Olympics PA", "Villanova Band", "Blue Key Society"],
    "website": "https://www.villanova.edu",
    "admissionsUrl": "https://www1.villanova.edu/university/admissions"
  },
  {
    "name": "University of Texas at Austin",
    "region": "South",
    "state": "TX",
    "fullUndergrad": 41300,
    "gradRate": 88,
    "deadline": "December 1",
    "majorStrengths": ["Business", "Engineering", "Computer Science", "Communication"],
    "applications": 73000,
    "accepted": 19400,
    "outstate": 46500,
    "roomBoard": 13500,
    "books": 700,
    "personal": 3100,
    "phd": 92,
    "terminal": 96,
    "testOptional": false,
    "isPrivate": false,
    "satRange": [1280, 1500],
    "actRange": [29, 34],
    "promptHistory": ["2025: Share a time you had a difficult conversation.", "2024: Why are you interested in your first-choice major?"],
    "extracurricularHighlights": ["Plan II Honors", "Longhorn Startup", "Texas 4000"],
    "website": "https://www.utexas.edu",
    "admissionsUrl": "https://admissions.utexas.edu"
  },
  {
    "name": "Rice University",
    "region": "South",
    "state": "TX",
    "fullUndergrad": 4500,
    "gradRate": 95,
    "deadline": "January 4",
    "majorStrengths": ["Architecture", "Music", "Bioengineering", "Economics"],
    "applications": 36800,
    "accepted": 2900,
    "outstate": 62800,
    "roomBoard": 16000,
    "books": 800,
    "personal": 2800,
    "phd": 98,
    "terminal": 99,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1510, 1560],
    "actRange": [34, 36],
    "promptHistory": ["2025: The 'The Box' photo prompt.", "2024: Describe a community that is important to you."],
    "extracurricularHighlights": ["Residential College System", "Rice 360 Institute", "Baker Institute"],
    "website": "https://www.rice.edu",
    "admissionsUrl": "https://admission.rice.edu"
  },
  {
    "name": "University of Washington",
    "region": "West",
    "state": "WA",
    "fullUndergrad": 36800,
    "gradRate": 85,
    "deadline": "November 15",
    "majorStrengths": ["Computer Science", "Nursing", "Oceanography", "Informatics"],
    "applications": 62000,
    "accepted": 26000,
    "outstate": 42000,
    "roomBoard": 17000,
    "books": 900,
    "personal": 2400,
    "phd": 90,
    "terminal": 94,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1300, 1510],
    "actRange": [29, 34],
    "promptHistory": ["2024: How have you sought to learn about different communities?"],
    "extracurricularHighlights": ["Direct to Major CS", "Huskies in Cinema", "HUB Board"],
    "website": "https://www.uw.edu",
    "admissionsUrl": "https://admit.washington.edu"
  },
  {
    "name": "Carnegie Mellon University",
    "region": "Northeast",
    "state": "PA",
    "fullUndergrad": 7500,
    "gradRate": 92,
    "deadline": "January 1",
    "majorStrengths": ["Computer Science", "Drama", "Robotics", "Design"],
    "applications": 34000,
    "accepted": 3900,
    "outstate": 63500,
    "roomBoard": 18000,
    "books": 1000,
    "personal": 1500,
    "phd": 96,
    "terminal": 98,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1510, 1560],
    "actRange": [34, 35],
    "promptHistory": ["2024: Why Carnegie Mellon?", "2024: What is a problem you want to solve?"],
    "extracurricularHighlights": ["Buggy Racing", "Scotty Labs", "Lunar Gala"],
    "website": "https://www.cmu.edu",
    "admissionsUrl": "https://www.cmu.edu/admission"
  },
  {
    "name": "Georgia Institute of Technology",
    "region": "South",
    "state": "GA",
    "fullUndergrad": 19500,
    "gradRate": 93,
    "deadline": "January 5",
    "majorStrengths": ["Engineering", "Computer Science", "Business", "Architecture"],
    "applications": 50600,
    "accepted": 8100,
    "outstate": 32800,
    "roomBoard": 12500,
    "books": 800,
    "personal": 2000,
    "phd": 95,
    "terminal": 98,
    "testOptional": false,
    "isPrivate": false,
    "satRange": [1370, 1550],
    "actRange": [31, 35],
    "promptHistory": ["2024: Beyond rankings, why is Georgia Tech a good fit for you?", "2023: Describe your favorite high school tradition."],
    "extracurricularHighlights": ["Invention Studio (Makerspace)", "Vertically Integrated Projects (VIP)", "GT Motorsports"],
    "website": "https://www.gatech.edu",
    "admissionsUrl": "https://admission.gatech.edu"
  },
  {
    "name": "Northeastern University",
    "region": "Northeast",
    "state": "MA",
    "fullUndergrad": 22000,
    "gradRate": 91,
    "deadline": "January 1",
    "majorStrengths": ["Business", "Engineering", "Health Sciences", "Criminal Justice"],
    "applications": 96300,
    "accepted": 6500,
    "outstate": 62300,
    "roomBoard": 19400,
    "books": 1000,
    "personal": 1500,
    "phd": 92,
    "terminal": 96,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1450, 1530],
    "actRange": [33, 35],
    "promptHistory": ["2024: No supplemental essays required (Common App Personal Statement only)."],
    "extracurricularHighlights": ["Co-op Program (Experiential Learning)", "IDEA Venture Accelerator", "Dialogue of Civilizations"],
    "website": "https://www.northeastern.edu",
    "admissionsUrl": "https://admissions.northeastern.edu"
  },
  {
    "name": "Pomona College",
    "region": "West",
    "state": "CA",
    "fullUndergrad": 1700,
    "gradRate": 97,
    "deadline": "January 8",
    "majorStrengths": ["Economics", "Mathematics", "Biology", "Philosophy"],
    "applications": 12000,
    "accepted": 800,
    "outstate": 64500,
    "roomBoard": 20400,
    "books": 900,
    "personal": 1200,
    "phd": 100,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1470, 1550],
    "actRange": [33, 35],
    "promptHistory": ["2024: What is the biggest problem you want to solve?", "2023: Describe a time you had a difficult conversation."],
    "extracurricularHighlights": ["Claremont Consortium Access", "Pomona Student Farm", "Outdoor Education Center"],
    "website": "https://www.pomona.edu",
    "admissionsUrl": "https://www.pomona.edu/admissions"
  },
  {
    "name": "Purdue University",
    "region": "Midwest",
    "state": "IN",
    "fullUndergrad": 38000,
    "gradRate": 84,
    "deadline": "January 15",
    "majorStrengths": ["Flight/Aviation", "Industrial Engineering", "Agriculture", "Pharmacy"],
    "applications": 72000,
    "accepted": 36000,
    "outstate": 28800,
    "roomBoard": 10500,
    "books": 1000,
    "personal": 2000,
    "phd": 92,
    "terminal": 95,
    "testOptional": false,
    "isPrivate": false,
    "satRange": [1210, 1450],
    "actRange": [27, 33],
    "promptHistory": ["2025: Why Purdue?", "2024: Briefly discuss your reasons for pursuing your chosen major."],
    "extracurricularHighlights": ["All-American Marching Band", "Purdue Grand Prix", "Epics (Service Learning)"],
    "website": "https://www.purdue.edu",
    "admissionsUrl": "https://www.admissions.purdue.edu"
  },
  {
    "name": "University of Virginia",
    "region": "South",
    "state": "VA",
    "fullUndergrad": 17500,
    "gradRate": 94,
    "deadline": "January 5",
    "majorStrengths": ["Architecture", "History", "Commerce", "Economics"],
    "applications": 56500,
    "accepted": 9200,
    "outstate": 58000,
    "roomBoard": 14000,
    "books": 1100,
    "personal": 2500,
    "phd": 95,
    "terminal": 98,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1390, 1530],
    "actRange": [32, 35],
    "promptHistory": ["2025: What is a favorite word and why?", "2024: Describe a community you are a part of."],
    "extracurricularHighlights": ["The Lawn Residential", "Madison House (Service)", "Cavalier Daily"],
    "website": "https://www.virginia.edu",
    "admissionsUrl": "https://admission.virginia.edu"
  },
  {
    "name": "Georgia State University",
    "region": "South",
    "state": "GA",
    "fullUndergrad": 28000,
    "gradRate": 56,
    "deadline": "April 1",
    "majorStrengths": ["Business", "Computer Science", "Film & Media", "Criminal Justice"],
    "applications": 32000,
    "accepted": 21000,
    "outstate": 23000,
    "roomBoard": 16000,
    "books": 1200,
    "personal": 3000,
    "phd": 85,
    "terminal": 90,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1050, 1250],
    "actRange": [20, 27],
    "promptHistory": ["2024: Standard Common App essay."],
    "extracurricularHighlights": ["Creative Media Industries Institute", "GSU Signal", "Panther Hackers"],
    "website": "https://www.gsu.edu",
    "admissionsUrl": "https://admissions.gsu.edu"
  },
  {
    "name": "University of Southern California",
    "region": "West",
    "state": "CA",
    "fullUndergrad": 21000,
    "gradRate": 92,
    "deadline": "January 15",
    "majorStrengths": ["Cinematic Arts", "Business Administration", "Communications", "Real Estate"],
    "applications": 82000,
    "accepted": 8000,
    "outstate": 69000,
    "roomBoard": 19000,
    "books": 1200,
    "personal": 2800,
    "phd": 94,
    "terminal": 97,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1450, 1550],
    "actRange": [32, 35],
    "promptHistory": ["2025: Describe your 'dream' class.", "2024: Favorite snack (short answer list)."],
    "extracurricularHighlights": ["USC Trojan Marching Band", "Visions and Voices", "Daily Trojan"],
    "website": "https://www.usc.edu",
    "admissionsUrl": "https://admission.usc.edu"
  },
  {
    "name": "Case Western Reserve University",
    "region": "Midwest",
    "state": "OH",
    "fullUndergrad": 6000,
    "gradRate": 85,
    "deadline": "January 15",
    "majorStrengths": ["Nursing", "Biomedical Engineering", "Management", "Music"],
    "applications": 39000,
    "accepted": 10500,
    "outstate": 63000,
    "roomBoard": 17800,
    "books": 1200,
    "personal": 2000,
    "phd": 94,
    "terminal": 96,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1410, 1520],
    "actRange": [32, 35],
    "promptHistory": ["2024: Common App essay + optional personal statement."],
    "extracurricularHighlights": ["Think[box] Makerspace", "Case Rocket Team", "Spartan Ambassadors"],
    "website": "https://case.edu",
    "admissionsUrl": "https://case.edu/admission"
  },
  {
    "name": "Clemson University",
    "region": "South",
    "state": "SC",
    "fullUndergrad": 22500,
    "gradRate": 85,
    "deadline": "January 2",
    "majorStrengths": ["Automotive Engineering", "Marketing", "Agriculture", "Architecture"],
    "applications": 60000,
    "accepted": 22000,
    "outstate": 38000,
    "roomBoard": 13000,
    "books": 1100,
    "personal": 2800,
    "phd": 88,
    "terminal": 92,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1230, 1400],
    "actRange": [27, 32],
    "promptHistory": ["2024: Describe your interest in your selected major."],
    "extracurricularHighlights": ["Tiger Band", "Clemson Formula SAE", "Solid Green Service"],
    "website": "https://www.clemson.edu",
    "admissionsUrl": "https://www.clemson.edu/admissions"
  },
  {
    "name": "Colorado School of Mines",
    "region": "West",
    "state": "CO",
    "fullUndergrad": 5700,
    "gradRate": 83,
    "deadline": "January 15",
    "majorStrengths": ["Mining Engineering", "Geology", "Petroleum Engineering", "Physics"],
    "applications": 12000,
    "accepted": 6800,
    "outstate": 41000,
    "roomBoard": 16500,
    "books": 1200,
    "personal": 2000,
    "phd": 90,
    "terminal": 94,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1330, 1480],
    "actRange": [30, 34],
    "promptHistory": ["2024: Why Mines?", "2024: Describe a challenge you overcame."],
    "extracurricularHighlights": ["M-Climb", "Colorado Space Grant", "Engineering Days"],
    "website": "https://www.mines.edu",
    "admissionsUrl": "https://www.mines.edu/admissions"
  },
  {
    "name": "Bowdoin College",
    "region": "Northeast",
    "state": "ME",
    "fullUndergrad": 1900,
    "gradRate": 95,
    "deadline": "January 5",
    "majorStrengths": ["Government", "Economics", "Environmental Studies", "Biology"],
    "applications": 11000,
    "accepted": 850,
    "outstate": 64000,
    "roomBoard": 17500,
    "books": 800,
    "personal": 1200,
    "phd": 99,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1420, 1530],
    "actRange": [32, 35],
    "promptHistory": ["2025: The 'Offer of the College' response.", "2024: Why Bowdoin?"],
    "extracurricularHighlights": ["Bowdoin Outing Club", "McKeen Center for Common Good", "The Orient"],
    "website": "https://www.bowdoin.edu",
    "admissionsUrl": "https://www.bowdoin.edu/admissions"
  },
  {
    "name": "Ohio State University",
    "region": "Midwest",
    "state": "OH",
    "fullUndergrad": 47000,
    "gradRate": 87,
    "deadline": "January 15",
    "majorStrengths": ["Supply Chain Management", "Psychology", "Nursing", "Finance"],
    "applications": 71000,
    "accepted": 34000,
    "outstate": 36500,
    "roomBoard": 14000,
    "books": 1000,
    "personal": 2500,
    "phd": 93,
    "terminal": 96,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1260, 1450],
    "actRange": [27, 33],
    "promptHistory": ["2024: What do you hope to accomplish at Ohio State?"],
    "extracurricularHighlights": ["The Best Damn Band in the Land", "Student Life Disability Services", "Buckeyethon"],
    "website": "https://www.osu.edu",
    "admissionsUrl": "https://undergrad.osu.edu"
  },
  {
    "name": "Wake Forest University",
    "region": "South",
    "state": "NC",
    "fullUndergrad": 5500,
    "gradRate": 88,
    "deadline": "January 1",
    "majorStrengths": ["Accounting", "Health & Exercise Science", "Communications", "Business"],
    "applications": 17500,
    "accepted": 3500,
    "outstate": 65000,
    "roomBoard": 18000,
    "books": 1100,
    "personal": 2400,
    "phd": 95,
    "terminal": 97,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1380, 1500],
    "actRange": [30, 33],
    "promptHistory": ["2025: List the books you read this summer.", "2024: What is your favorite quote?"],
    "extracurricularHighlights": ["Pro Humanitate (Service)", "Wake Forest Debate", "Old Gold & Black"],
    "website": "https://www.wfu.edu",
    "admissionsUrl": "https://admissions.wfu.edu"
  },
  {
    "name": "University of Wisconsin-Madison",
    "region": "Midwest",
    "state": "WI",
    "fullUndergrad": 35000,
    "gradRate": 89,
    "deadline": "January 15",
    "majorStrengths": ["Biochemistry", "Education", "Sociology", "Chemical Engineering"],
    "applications": 64000,
    "accepted": 28000,
    "outstate": 40500,
    "roomBoard": 13500,
    "books": 1200,
    "personal": 2600,
    "phd": 94,
    "terminal": 97,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1350, 1510],
    "actRange": [29, 34],
    "promptHistory": ["2025: Why UW-Madison?", "2024: Describe a time you showed leadership."],
    "extracurricularHighlights": ["Wisconsin Union Directorate", "Hoofers Sailing Club", "The Badger Herald"],
    "website": "https://www.wisc.edu",
    "admissionsUrl": "https://admissions.wisc.edu"
  },
  {
    "name": "Davidson College",
    "region": "South",
    "state": "NC",
    "fullUndergrad": 1900,
    "gradRate": 93,
    "deadline": "January 5",
    "majorStrengths": ["Economics", "Biology", "Political Science", "English"],
    "applications": 6500,
    "accepted": 1100,
    "outstate": 60000,
    "roomBoard": 17200,
    "books": 900,
    "personal": 1500,
    "phd": 100,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1360, 1500],
    "actRange": [31, 34],
    "promptHistory": ["2024: What is a problem you want to solve?", "2023: Why Davidson?"],
    "extracurricularHighlights": ["Honor Code System", "Davidson Outdoors", "The Davidsonian"],
    "website": "https://www.davidson.edu",
    "admissionsUrl": "https://www.davidson.edu/admission-and-financial-aid"
  },
  {
    "name": "Santa Clara University",
    "region": "West",
    "state": "CA",
    "fullUndergrad": 6100,
    "gradRate": 91,
    "deadline": "January 7",
    "majorStrengths": ["Finance", "Silicon Valley Management", "Psychology", "Computer Science"],
    "applications": 18500,
    "accepted": 9200,
    "outstate": 61000,
    "roomBoard": 18200,
    "books": 1200,
    "personal": 2500,
    "phd": 94,
    "terminal": 97,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1330, 1490],
    "actRange": [30, 34],
    "promptHistory": ["2025: Why SCU?", "2024: Describe how you will contribute to the Silicon Valley community."],
    "extracurricularHighlights": ["SCU Bronco Pep Band", "Leavey School of Business Peer Advising", "SCCAP (Service)"],
    "website": "https://www.scu.edu",
    "admissionsUrl": "https://www.scu.edu/admission"
  },
  {
    "name": "Duke University",
    "region": "South",
    "state": "NC",
    "fullUndergrad": 6800,
    "gradRate": 96,
    "deadline": "January 2",
    "majorStrengths": ["Public Policy", "Economics", "Biology", "Global Health"],
    "applications": 54000,
    "accepted": 2800,
    "outstate": 66000,
    "roomBoard": 18500,
    "books": 600,
    "personal": 2200,
    "phd": 99,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1510, 1570],
    "actRange": [34, 35],
    "promptHistory": ["2025: Describe a perspective that makes you unique.", "2024: Optional prompt on LGBTQ+ identity."],
    "extracurricularHighlights": ["DukeEngage", "Cameron Crazies", "Robertson Scholars"],
    "website": "https://www.duke.edu",
    "admissionsUrl": "https://admissions.duke.edu"
  },
  {
    "name": "UC Berkeley",
    "region": "West",
    "state": "CA",
    "fullUndergrad": 32800,
    "gradRate": 93,
    "deadline": "November 30",
    "majorStrengths": ["Environmental Science", "Political Science", "EECS", "English"],
    "applications": 126000,
    "accepted": 14400,
    "outstate": 48500,
    "roomBoard": 21000,
    "books": 1100,
    "personal": 2000,
    "phd": 96,
    "terminal": 98,
    "testOptional": true,
    "isPrivate": false,
    "satRange": null,
    "actRange": null,
    "promptHistory": ["2025: UC Personal Insight Questions (8 options, pick 4)."],
    "extracurricularHighlights": ["ASUC Student Gov", "Daily Californian", "DeCal Classes"],
    "website": "https://www.berkeley.edu",
    "admissionsUrl": "https://admissions.berkeley.edu"
  },
  {
    "name": "University of North Carolina",
    "region": "South",
    "state": "NC",
    "fullUndergrad": 20500,
    "gradRate": 91,
    "deadline": "January 15",
    "majorStrengths": ["Biomedical Engineering", "Journalism", "Psychology", "Dentistry"],
    "applications": 66500,
    "accepted": 10200,
    "outstate": 41000,
    "roomBoard": 13000,
    "books": 1000,
    "personal": 1800,
    "phd": 93,
    "terminal": 96,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1400, 1530],
    "actRange": [28, 34],
    "promptHistory": ["2025: Describe a time you demonstrated intellectual curiosity."],
    "extracurricularHighlights": ["Hussman School Projects", "The Daily Tar Heel", "APPLES Service Learning"],
    "website": "https://www.unc.edu",
    "admissionsUrl": "https://admissions.unc.edu"
  },
  {
    "name": "Northwestern University",
    "region": "Midwest",
    "state": "IL",
    "fullUndergrad": 8600,
    "gradRate": 95,
    "deadline": "January 2",
    "majorStrengths": ["Journalism", "Theater", "Materials Science", "Economics"],
    "applications": 52000,
    "accepted": 3600,
    "outstate": 67000,
    "roomBoard": 20500,
    "books": 1200,
    "personal": 2200,
    "phd": 99,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1500, 1560],
    "actRange": [33, 35],
    "promptHistory": ["2025: Why Northwestern?", "2024: Describe a community you belong to."],
    "extracurricularHighlights": ["Dance Marathon", "Medill News Service", "Mayfest"],
    "website": "https://www.northwestern.edu",
    "admissionsUrl": "https://admissions.northwestern.edu"
  },
  {
    "name": "Johns Hopkins University",
    "region": "Northeast",
    "state": "MD",
    "fullUndergrad": 5300,
    "gradRate": 94,
    "deadline": "January 2",
    "majorStrengths": ["Public Health", "Molecular Biology", "International Studies", "Writing Seminars"],
    "applications": 46000,
    "accepted": 2900,
    "outstate": 65000,
    "roomBoard": 18500,
    "books": 1000,
    "personal": 1400,
    "phd": 98,
    "terminal": 99,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1530, 1560],
    "actRange": [34, 36],
    "promptHistory": ["2024: Collaborating with people of different backgrounds.", "2023: Personal statement supplement."],
    "extracurricularHighlights": ["JHU Thread", "Spring Fair", "Hopkins Biotech Network"],
    "website": "https://www.jhu.edu",
    "admissionsUrl": "https://apply.jhu.edu"
  },
  {
    "name": "Emory University",
    "region": "South",
    "state": "GA",
    "fullUndergrad": 7100,
    "gradRate": 91,
    "deadline": "January 1",
    "majorStrengths": ["Nursing", "Business", "Neuroscience", "History"],
    "applications": 34500,
    "accepted": 4500,
    "outstate": 62500,
    "roomBoard": 18000,
    "books": 1100,
    "personal": 2500,
    "phd": 95,
    "terminal": 98,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1460, 1540],
    "actRange": [33, 35],
    "promptHistory": ["2025: Tell us about something you want to learn more about.", "2024: A text you read that changed your mind."],
    "extracurricularHighlights": ["Oxford College Transition", "Dooley's Week", "Volunteer Emory"],
    "website": "https://www.emory.edu",
    "admissionsUrl": "https://apply.emory.edu"
  },
  {
    "name": "Tulane University",
    "region": "South",
    "state": "LA",
    "fullUndergrad": 7400,
    "gradRate": 86,
    "deadline": "January 15",
    "majorStrengths": ["Public Health", "Business", "Architecture", "Political Science"],
    "applications": 32600,
    "accepted": 4500,
    "outstate": 65000,
    "roomBoard": 18800,
    "books": 1000,
    "personal": 2000,
    "phd": 92,
    "terminal": 95,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1410, 1500],
    "actRange": [31, 34],
    "promptHistory": ["2025: Why Tulane?", "2024: Describe your commitment to service."],
    "extracurricularHighlights": ["Crawfest", "Center for Public Service", "Glassblowing Club"],
    "website": "https://www.tulane.edu",
    "admissionsUrl": "https://admission.tulane.edu"
  },
  {
    "name": "University of Notre Dame",
    "region": "Midwest",
    "state": "IN",
    "fullUndergrad": 8900,
    "gradRate": 97,
    "deadline": "January 1",
    "majorStrengths": ["Theology", "Finance", "Aerospace Engineering", "Pre-Professional Studies"],
    "applications": 29000,
    "accepted": 3500,
    "outstate": 63000,
    "roomBoard": 17800,
    "books": 1000,
    "personal": 2200,
    "phd": 98,
    "terminal": 99,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1450, 1540],
    "actRange": [33, 35],
    "promptHistory": ["2025: What is distinctive about your personal story?", "2024: Blessed Basil Moreau quote response."],
    "extracurricularHighlights": ["Dorm Spirit / Inter-Hall Sports", "Center for Social Concerns", "Student International Business Council"],
    "website": "https://www.nd.edu",
    "admissionsUrl": "https://admissions.nd.edu"
  },
  {
    "name": "Swarthmore College",
    "region": "Northeast",
    "state": "PA",
    "fullUndergrad": 1650,
    "gradRate": 94,
    "deadline": "January 4",
    "majorStrengths": ["Political Science", "Biology", "Economics", "Engineering"],
    "applications": 13100,
    "accepted": 1000,
    "outstate": 64000,
    "roomBoard": 19500,
    "books": 800,
    "personal": 1200,
    "phd": 100,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1500, 1550],
    "actRange": [33, 35],
    "promptHistory": ["2025: Why Swarthmore?", "2024: Share a time you engaged with a difficult topic."],
    "extracurricularHighlights": ["Honors Program", "Scott Arboretum", "Amherst-Williams-Wesleyan-Swarthmore matches"],
    "website": "https://www.swarthmore.edu",
    "admissionsUrl": "https://www.swarthmore.edu/admissions-aid"
  },
  {
    "name": "Amherst College",
    "region": "Northeast",
    "state": "MA",
    "fullUndergrad": 1900,
    "gradRate": 95,
    "deadline": "January 1",
    "majorStrengths": ["English", "History", "Physics", "American Studies"],
    "applications": 15000,
    "accepted": 1100,
    "outstate": 68000,
    "roomBoard": 18500,
    "books": 1000,
    "personal": 1500,
    "phd": 100,
    "terminal": 100,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1470, 1550],
    "actRange": [33, 35],
    "promptHistory": ["2025: Respond to a quote from an alumnus.", "2024: Open curriculum reflection."],
    "extracurricularHighlights": ["Five College Consortium", "Mead Art Museum", "Marsh Arts House"],
    "website": "https://www.amherst.edu",
    "admissionsUrl": "https://www.amherst.edu/admission"
  },
  {
    "name": "Boston College",
    "region": "Northeast",
    "state": "MA",
    "fullUndergrad": 9700,
    "gradRate": 93,
    "deadline": "January 1",
    "majorStrengths": ["Finance", "Nursing", "Psychology", "Philosophy"],
    "applications": 39700,
    "accepted": 5500,
    "outstate": 72000,
    "roomBoard": 19300,
    "books": 1100,
    "personal": 2200,
    "phd": 94,
    "terminal": 96,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1440, 1520],
    "actRange": [33, 35],
    "promptHistory": ["2025: Conversations about climate change or human rights.", "2024: The common good and Jesuit values."],
    "extracurricularHighlights": ["PULSE Program", "Appalachia Volunteers", "Baldwin Ambassadors"],
    "website": "https://www.bc.edu",
    "admissionsUrl": "https://www.bc.edu/admission"
  },
  {
    "name": "WashU in St. Louis",
    "region": "Midwest",
    "state": "MO",
    "fullUndergrad": 8100,
    "gradRate": 94,
    "deadline": "January 2",
    "majorStrengths": ["Art", "Design", "Biology", "Entrepreneurship"],
    "applications": 32800,
    "accepted": 3950,
    "outstate": 64500,
    "roomBoard": 20400,
    "books": 1000,
    "personal": 2500,
    "phd": 98,
    "terminal": 99,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1500, 1570],
    "actRange": [33, 35],
    "promptHistory": ["2024: Beyond your major, what else will you explore at WashU?"],
    "extracurricularHighlights": ["Student Union", "Uncle Joe's Peer Counseling", "KWUR Radio"],
    "website": "https://wustl.edu",
    "admissionsUrl": "https://admissions.wustl.edu"
  },
  {
    "name": "Boston University",
    "region": "Northeast",
    "state": "MA",
    "fullUndergrad": 17800,
    "gradRate": 88,
    "deadline": "January 4",
    "majorStrengths": ["Communication", "Biomedical Engineering", "International Relations", "Business"],
    "applications": 80800,
    "accepted": 8800,
    "outstate": 65000,
    "roomBoard": 18600,
    "books": 1200,
    "personal": 2800,
    "phd": 92,
    "terminal": 95,
    "testOptional": true,
    "isPrivate": true,
    "satRange": [1400, 1510],
    "actRange": [32, 34],
    "promptHistory": ["2025: Why BU?", "2024: A time you were a leader or active community member."],
    "extracurricularHighlights": ["Kilachand Honors College", "Student Village", "BU Spark!"],
    "website": "https://www.bu.edu",
    "admissionsUrl": "https://www.bu.edu/admissions"
  },
  {
    "name": "UCLA",
    "region": "West",
    "state": "CA",
    "fullUndergrad": 32700,
    "gradRate": 92,
    "deadline": "November 30",
    "majorStrengths": ["Film/Television", "Psychology", "Life Sciences", "Political Science"],
    "applications": 146000,
    "accepted": 13100,
    "outstate": 49000,
    "roomBoard": 18200,
    "books": 1300,
    "personal": 2600,
    "phd": 95,
    "terminal": 98,
    "testOptional": true,
    "isPrivate": false,
    "satRange": null,
    "actRange": null,
    "promptHistory": ["2025: UC Personal Insight Questions (Shared with Berkeley)."],
    "extracurricularHighlights": ["Bruin Shelter", "Spring Sing", "Daily Bruin"],
    "website": "https://www.ucla.edu",
    "admissionsUrl": "https://admission.ucla.edu"
  },
  {
    "name": "University of Michigan",
    "region": "Midwest",
    "state": "MI",
    "fullUndergrad": 32600,
    "gradRate": 94,
    "deadline": "February 1",
    "majorStrengths": ["Business", "Engineering", "Psychology", "Political Science"],
    "applications": 87000,
    "accepted": 15600,
    "outstate": 58000,
    "roomBoard": 14200,
    "books": 1100,
    "personal": 2500,
    "phd": 96,
    "terminal": 99,
    "testOptional": true,
    "isPrivate": false,
    "satRange": [1350, 1530],
    "actRange": [31, 34],
    "promptHistory": ["2024: Everyone belongs to many communities. Describe one.", "2024: Describe a unique quality that will help you contribute to UM."],
    "extracurricularHighlights": ["Michigan Marching Band", "Ross Investment Club", "UROP (Research)"],
    "website": "https://umich.edu",
    "admissionsUrl": "https://admissions.umich.edu"
  }
];
